import 'package:dio/dio.dart';
import 'dart:developer' as developer;

class ApiService {
  final Dio _dio;

  ApiService({
    required String githubToken,
    required String aiProvider,
    required String aiApiKey,
  }) : _dio = Dio(BaseOptions(
          baseUrl: 'http://127.0.0.1:8000/api/v1',
          connectTimeout: const Duration(seconds: 15),
          receiveTimeout: const Duration(seconds: 120),
          headers: {
            if (githubToken.isNotEmpty) 'x-github-token': githubToken,
            if (aiProvider.isNotEmpty) 'x-ai-provider': aiProvider,
            if (aiApiKey.isNotEmpty) 'x-ai-api-key': aiApiKey,
          },
        ));

  // Get User Stats
  Future<Map<String, dynamic>> getUserStats(String owner) async {
    try {
      final response = await _dio.get('/records/stats/$owner');
      return response.data;
    } catch (e) {
      developer.log('Error fetching user stats: $e');
      rethrow;
    }
  }

  // Generate Trap PR (Auto) - language & branch auto-generated by backend
  Future<Map<String, dynamic>> generateAutoTrapPR(
      String owner, String repo, String path) async {
    try {
      final data = <String, dynamic>{};
      if (path.isNotEmpty) {
        data['path'] = path;
      }
      
      final response = await _dio.post(
        '/agent/auto-trap-pr/$owner/$repo',
        data: data,
      );
      return response.data;
    } catch (e) {
      developer.log('Error generating auto trap PR: $e');
      rethrow;
    }
  }

  // Score Review
  Future<Map<String, dynamic>> scoreReview(
      String owner, String repo, int prNumber) async {
    try {
      final response = await _dio.post('/agent/score-review/$owner/$repo/$prNumber');
      return response.data;
    } catch (e) {
      developer.log('Error scoring review: $e');
      rethrow;
    }
  }

  // Start comment watcher (polling) for a specific PR
  Future<Map<String, dynamic>> startWatcher(String owner, String repo, int prNumber) async {
    try {
      final response = await _dio.post('/agent/start-watcher/$owner/$repo/$prNumber');
      return response.data;
    } catch (e) {
      developer.log('Error starting watcher: $e');
      rethrow;
    }
  }
}
