from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from github import Github
from github import Auth
import os
from dotenv import load_dotenv

from google import genai
from google.genai import types
import json
# .envファイルから環境変数を読み込む
load_dotenv()

app = FastAPI()

# GitHubクライアントの初期化
github_token = os.getenv("GITHUB_TOKEN")
if not github_token:
    raise RuntimeError("GITHUB_TOKENが設定されていません。.envファイルを確認してください。")

# Geminiクライアントの初期化
gemini_api_key = os.getenv("GEMINI_API_KEY")
if not gemini_api_key:
    raise RuntimeError("GEMINI_API_KEYが設定されていません。.envファイルを確認してください。")

# Clientは自動的に環境変数 GEMINI_API_KEY を読み込みます
ai_client = genai.Client()

auth = Auth.Token(github_token)
g = Github(auth=auth)

@app.get("/")
def read_root():
    return {"message": "Trap-PR Agent API is running!"}

@app.get("/api/v1/github/test/{owner}/{repo}")
def test_github_connection(owner: str, repo: str):
    """
    指定したリポジトリの情報を取得するテストエンドポイント
    """
    try:
        # リポジトリの取得 (例: "tiangolo/fastapi")
        repo_name = f"{owner}/{repo}"
        repository = g.get_repo(repo_name)
        
        return {
            "status": "success",
            "repo_name": repository.full_name,
            "description": repository.description,
            "stars": repository.stargazers_count,
            "url": repository.html_url
        }
    except Exception as e:
        raise HTTPException(status_code=404, detail=f"リポジトリの取得に失敗しました: {str(e)}")
@app.get("/api/v1/github/code/{owner}/{repo}")

def get_repository_content(owner: str, repo: str, path: str = ""):
    """
    指定したリポジトリの特定のパス（ディレクトリまたはファイル）の情報を取得する
    """
    try:
        repo_name = f"{owner}/{repo}"
        repository = g.get_repo(repo_name)
        
        # pathが指定されていない場合はルートディレクトリ（直下）を取得
        contents = repository.get_contents(path)
        
        # ディレクトリの場合（中身がリストで返ってくる）
        if isinstance(contents, list):
            files = []
            for content in contents:
                files.append({
                    "name": content.name,
                    "path": content.path,
                    "type": content.type # "dir" または "file"
                })
            return {
                "status": "success",
                "type": "directory",
                "path": path if path else "/",
                "contents": files
            }
        
        # 単一ファイルの場合
        else:
            # GitHub APIから取得したファイルの中身はエンコードされているため、UTF-8にデコードする
            decoded_text = contents.decoded_content.decode("utf-8")
            return {
                "status": "success",
                "type": "file",
                "name": contents.name,
                "path": contents.path,
                "content": decoded_text
            }
            
    except Exception as e:
        raise HTTPException(status_code=404, detail=f"対象の取得に失敗しました。パスが間違っているか、権限がありません: {str(e)}")
    # --- ここから追記 ---

class PRCreateRequest(BaseModel):
    """PR作成時のリクエストボディの定義"""
    branch_name: str = "trap-pr-test-branch"
    commit_message: str = "Add trap code test"
    pr_title: str = "[Trap] テスト用の罠PR"
    pr_body: str = "これはTrap-PR Agentのテストで自動生成されたPRです。"

@app.post("/api/v1/github/pr/{owner}/{repo}")
def create_dummy_pr(owner: str, repo: str, req: PRCreateRequest):
    """
    指定したリポジトリに新しいブランチを作成し、ダミーファイルを追加してPRを作成する
    """
    try:
        repo_name = f"{owner}/{repo}"
        repository = g.get_repo(repo_name)
        
        # 1. デフォルトブランチ（mainなど）を取得して、最新のコミットSHAを取得
        default_branch = repository.default_branch
        base_ref = repository.get_branch(default_branch)
        
        # 2. 新しいブランチを作成
        # 注意: 既に同名のブランチが存在する場合はエラーになります
        repository.create_git_ref(ref=f"refs/heads/{req.branch_name}", sha=base_ref.commit.sha)
        
        # 3. テスト用のファイルを新しいブランチに作成
        repository.create_file(
            path="trap_test_dummy.txt",
            message=req.commit_message,
            content="This is a dummy trap code generated by Trap-PR Agent.",
            branch=req.branch_name
        )
        
        # 4. PR（Pull Request）を作成
        pr = repository.create_pull(
            title=req.pr_title,
            body=req.pr_body,
            head=req.branch_name,
            base=default_branch
        )
        
        return {
            "status": "success", 
            "message": "PRの作成に成功しました！",
            "pr_url": pr.html_url
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PRの作成に失敗しました: {str(e)}")

# --- ここからファイル最下部に追記 ---

class TrapGenerationRequest(BaseModel):
    """罠生成リクエストのデータ構造"""
    target_code: str  # 読み込ませる対象のソースコード
    file_name: str    # 対象ファイルの名称（例: "auth.py", "UserController.java"）
    language: str     # プログラミング言語（例: "python", "javascript"）

class TrapGenerationResponse(BaseModel):
    """Geminiから確実にこの構造で返してもらうためのPydanticモデル"""
    feature_proposal: str  # 新機能の提案（何を追加するか）
    perfect_code: str      # 脆弱性やバグを含まない、完璧な実装コード
    trap_code: str         # 完璧なコードをベースに、意図的な脆弱性や欠陥を仕込んだコード
    trap_explanation: str  # 【解説用】どんな罠（脆弱性）をどこに仕込んだか（ユーザーには隠す正解データ）

@app.post("/api/v1/agent/generate-trap", response_model=TrapGenerationResponse)
def generate_trap_code(req: TrapGenerationRequest):
    """
    既存のコードを読み込み、新機能の提案と、それに応じた「完璧なコード」および「罠コード」を生成する
    """
    
    # Geminiに与えるシステム指示（役割の定義）プロンプト
    system_instruction = (
        "あなたは悪意ある開発者を演じるAIエージェントであり、同時に優秀なプログラミング講師です。\n"
        "提出された既存のソースコードを読み込み、プロジェクトがより便利になる『新機能』を1つ提案してください。\n"
        "そして、その新機能を実現するための『問題を含まない完璧なコード』を作成してください。\n"
        "最後に、その完璧なコードをベースに、構造的な欠陥やセキュリティ上の罠（脆弱性）を巧妙に仕込んだ『罠コード』を生成してください。\n"
        "罠コードは、一見すると正常に動くように見え、コードレビューをすり抜けるような巧妙なものにしてください。\n"
        "出力は必ず指定されたJSONスキーマに従ってください。"
    )

    # ユーザーからの入力プロンプト
    user_prompt = f"""
    対象ファイル名: {req.file_name}
    言語: {req.language}
    
    【既存のソースコード】
    ```
    {req.target_code}
    ```
    """

    try:
        # Gemini API の呼び出し (構造化出力を強制)
        response = ai_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                # 応答の形式をJSONに、かつ作成したPydanticモデルの構造を強制
                response_mime_type="application/json",
                response_schema=TrapGenerationResponse,
                temperature=0.7,
            ),
        )
        
        # response.text は自動的にTrapGenerationResponseの構造に沿ったJSON文字列になっているため、パースして返却
        result_data = json.loads(response.text)
        return result_data

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Geminiによるコード生成に失敗しました: {str(e)}")
    
# --- ここからファイル最下部に追記 ---

class AutoTrapPRRequest(BaseModel):
    """全自動罠PR生成リクエスト"""
    path: str           # ターゲットにする既存ファイルのパス（例: "main.py" や "src/auth.js"）
    language: str       # プログラミング言語（例: "python", "javascript"）
    branch_name: str = "trap-challenge-branch" # 作成するブランチ名

class AutoTrapPRResponse(BaseModel):
    """フロントエンドや記録用に返すレスポンス"""
    status: str
    message: str
    pr_url: str         # 生成されたGitHub PRのURL
    feature_proposal: str # AIが提案した新機能の内容
    perfect_code: str   # 完璧なコード（正解コードとして後で使うため）
    trap_code: str      # 実際に仕込まれた罠コード
    trap_explanation: str # 罠の解説（裏側のデータベース記録用）

@app.post("/api/v1/agent/auto-trap-pr/{owner}/{repo}", response_model=AutoTrapPRResponse)
def auto_trap_pr(owner: str, repo: str, req: AutoTrapPRRequest):
    """
    【コア機能】GitHubからコードを自動取得し、Geminiで罠を生成させ、自動でPRを作成する
    """
    try:
        # ----------------------------------------------------
        # STEP 1: GitHubから既存のターゲットコードを取得
        # ----------------------------------------------------
        repo_name = f"{owner}/{repo}"
        repository = g.get_repo(repo_name)
        
        # 指定されたパスのファイルコンテンツを取得
        contents = repository.get_contents(req.path)
        if isinstance(contents, list):
            raise HTTPException(status_code=400, detail="指定されたパスはディレクトリです。ファイルを指定してください。")
            
        target_code = contents.decoded_content.decode("utf-8")

        # ----------------------------------------------------
        # STEP 2: Gemini APIを呼び出して、罠コードを生成
        # ----------------------------------------------------
        system_instruction = (
            "あなたは悪意ある開発者を演じるAIエージェントであり、同時に優秀なプログラミング講師です。\n"
            "提出された既存のソースコードを読み込み、プロジェクトがより便利になる『新機能』を1つ提案してください。\n"
            "そして、その新機能を実現するための『問題を含まない完璧なコード』を作成してください。\n"
            "最後に、その完璧なコードをベースに、構造的な欠陥やセキュリティ上の罠（脆弱性）を巧妙に仕込んだ『罠コード』を生成してください。\n"
            "罠コードは、一見すると正常に動くように見え、コードレビューをすり抜けるような巧妙なものにしてください。\n"
            "出力は必ず指定されたJSONスキーマに従ってください。"
        )

        user_prompt = f"対象ファイル名: {contents.name}\n言語: {req.language}\n\n【既存のソースコード】\n```\n{target_code}\n```"

        # 前のステップで作った TrapGenerationResponse モデルを流用して構造化出力を得る
        ai_response = ai_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json",
                response_schema=TrapGenerationResponse, # 提案、完璧コード、罠コード、解説を含むスキーマ
                temperature=0.7,
            ),
        )
        
        # AIの返答をパース
        ai_data = json.loads(ai_response.text)

        # ----------------------------------------------------
        # STEP 3: 新しいブランチを作成し、罠コードで上書きしてPRを作成
        # ----------------------------------------------------
        default_branch = repository.default_branch
        base_ref = repository.get_branch(default_branch)
        
        # 新しいブランチを作成 (既に同名ブランチがある場合はエラーになるため注意)
        repository.create_git_ref(ref=f"refs/heads/{req.branch_name}", sha=base_ref.commit.sha)
        
        # 既存ファイルをAIが作った `trap_code` で上書き更新する
        repository.update_file(
            path=req.path,
            message=f"Feat: Add proposed feature for {contents.name}",
            content=ai_data["trap_code"],
            sha=contents.sha, # 上書きには既存ファイルのSHAが必要
            branch=req.branch_name
        )
        
        # GitHub上でPRを作成
        pr_title = f"[Trap Challenge] {ai_data['feature_proposal'][:40]}..."
        pr_body = (
            f"### 🚀 AIエージェントからの新機能提案\n"
            f"{ai_data['feature_proposal']}\n\n"
            f"--- \n"
            f"💡 **レビューアーへの挑戦**:\n"
            f"このPRのコードには、巧妙なバグやセキュリティ上の脆弱性（罠）が仕込まれています。\n"
            f"コードを注意深くレビューし、問題点を見つけてコメントで指摘してください！"
        )
        
        pr = repository.create_pull(
            title=pr_title,
            body=pr_body,
            head=req.branch_name,
            base=default_branch
        )

        # 全ての処理結果をまとめて返却
        return {
            "status": "success",
            "message": "既存コードの読み込みから、Geminiによる罠生成、GitHubへのPR作成まで正常に完了しました！",
            "pr_url": pr.html_url,
            "feature_proposal": ai_data["feature_proposal"],
            "perfect_code": ai_data["perfect_code"],
            "trap_code": ai_data["trap_code"],
            "trap_explanation": ai_data["trap_explanation"]
        }
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"全自動PR生成に失敗しました: {str(e)}")

# --- ここからファイル最下部に追記 ---

class ReviewScoreRequest(BaseModel):
    """レビュー採点リクエスト"""
    trap_explanation: str  # 採点基準となる、仕込んだ罠の解説（答え）

class ReviewScoreResponse(BaseModel):
    """Geminiからの採点結果を構造化するためのモデル"""
    is_correct: bool       # 罠を正しく指摘できているか（合格ラインに達しているか）
    score: int             # 採点スコア (0から100の間)
    feedback: str          # ユーザーへのフィードバック・解説メッセージ

@app.post("/api/v1/agent/score-review/{owner}/{repo}/{pr_number}")
def score_review(owner: str, repo: str, pr_number: int, req: ReviewScoreRequest):
    """
    指定されたPRのコメントを取得し、仕込まれた罠を指摘できているかをGeminiに採点させ、結果をPRにコメントする
    """
    try:
        # ----------------------------------------------------
        # STEP 1: GitHubからPRのコメントを取得
        # ----------------------------------------------------
        repo_name = f"{owner}/{repo}"
        repository = g.get_repo(repo_name)
        pull_request = repository.get_pull(pr_number)
        
        # PRに紐づくすべてのコメント（通常のコメントと、コード上のレビューコメント）を回収
        comments = []
        
        # 通常のPRコメントを取得
        for comment in pull_request.get_issue_comments():
            comments.append(f"{comment.user.login}: {comment.body}")
            
        # コード行に対するレビューコメントを取得
        for comment in pull_request.get_comments():
            comments.append(f"{comment.user.login} (on code): {comment.body}")
            
        if not comments:
            raise HTTPException(status_code=400, detail="PRにまだコメントが投稿されていません。レビューコメントを書き込んでから再度実行してください。")
            
        # コメント履歴を1つのテキストにまとめる
        user_reviews_text = "\n---\n".join(comments)

        # ----------------------------------------------------
        # STEP 2: Geminiにコメントを渡して採点させる
        # ----------------------------------------------------
        system_instruction = (
            "あなたは厳格でありながらも育成熱心なプログラミング講師です。\n"
            "ユーザー（開発者）がコードレビューとして残したコメントを読み、彼らが『仕込まれた罠（脆弱性や欠陥）』を正しく見抜けきれているかを評価してください。\n"
            "単に『バグがある』という指摘だけでなく、具体的にどの部分がどう危険か（例: ゼロ除算、SQLインジェクション、バックドア等）を言い当てているかを重視してください。\n"
            "出力は必ず指定されたJSONスキーマ（is_correct, score, feedback）に従ってください。\n"
            "feedback内では、ユーザーの指摘の良い点、足りない点をレビューし、最後に正解（罠の解説）を優しく教えてあげてください。"
        )

        user_prompt = f"""
        【仕込まれていた罠の解説（正解データ）】
        {req.trap_explanation}
        
        【ユーザーが残したレビューコメント一覧】
        {user_reviews_text}
        """

        ai_response = ai_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json",
                response_schema=ReviewScoreResponse,
                temperature=0.2, # 採点のブレを減らすため低めに設定
            ),
        )
        
        score_data = json.loads(ai_response.text)

        # ----------------------------------------------------
        # STEP 3: 採点結果をGitHubのPRに自動コメント投稿する
        # ----------------------------------------------------
        result_emoji = "🎉 【合格】" if score_data["is_correct"] else "❌ 【不合格/未達成】"
        
        github_comment_body = (
            f"## 🤖 Trap-PR Agent 採点結果\n"
            f"**判定:** {result_emoji}\n"
            f"**スコア:** `{score_data['score']} / 100` 点\n\n"
            f"### 💡 エージェントからのフィードバック\n"
            f"{score_data['feedback']}\n\n"
            f"--- \n"
            f"修業を続けて、さらなる罠を見破れるようになりましょう！"
        )
        
        # PRに結果を書き込む
        pull_request.create_issue_comment(github_comment_body)

        return {
            "is_correct": score_data["is_correct"],
            "score": score_data["score"],
            "feedback": score_data["feedback"],
            "message": "GitHubへの採点コメントの投稿が完了しました！"
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"採点処理に失敗しました: {str(e)}")